name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Get code
      - uses: actions/setup-node@v3
        name: Setup Node
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm install
        name: Install dependencies
      - run: npm test
        name: Run tests
